In [2]:
import numpy as np
array1 = np.array([1,2,3,4,5])

In [3]:
array2 = np.array([9,8,7,6,5])
array3 = array1 + array2
array3

array([10, 10, 10, 10, 10])

In [4]:
array4 = array3*10
array4

array([100, 100, 100, 100, 100])

In [5]:
np.empty((10,))

array([5.21398654e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       9.31054074e+242, 2.11020351e-052, 9.04749033e-043, 5.20285697e-090,
       5.00011980e+174, 3.44210187e+175])